Repository amaralc/lmp-platform, pull requests merged in 2020-02, with the labels that each got.

#3 Configurando Multer
  doc/02-iniciando-back-end-do-gobarber.md
  package.json
  src/config/multer.js
  src/routes.js
  tmp/uploads/ffbe7e90e37ed9e10f30fa0c643407c0.PNG
  yarn.lock
Labels: feature

#4 Adiciona avatar do usuario
  doc/02-iniciando-back-end-do-gobarber.md
  src/app/controllers/FileController.js
  src/app/models/.gitkeep
  src/app/models/File.js
  src/app/models/User.js
  src/config/.gitkeep
  src/database/index.js
  src/database/migrations/.gitkeep
  src/database/migrations/20200204181448-create-files.js
  src/database/migrations/20200204182326-add-avatar-field-to-users.js
  src/routes.js
  tmp/uploads/6b63e10ffbba191d9a67694fba0fe123.PNG
Labels: feature

#6 Configuração do multer e adição de avatar
  doc/02-iniciando-back-end-do-gobarber.md
  package.json
  src/app/controllers/FileController.js
  src/app/models/.gitkeep
  src/app/models/File.js
  src/app/models/User.js
  src/config/.gitkeep
  src/config/multer.js
  src/database/index.js
  src/database/migrations/.gitkeep
  src/database/migrations/20200204181448-create-files.js
  src/database/migrations/20200204182326-add-avatar-field-to-users.js
  src/routes.js
  tmp/uploads/6b63e10ffbba191d9a67694fba0fe123.PNG
  tmp/uploads/ffbe7e90e37ed9e10f30fa0c643407c0.PNG
  yarn.lock
Labels: feature

#8 API-CLIENT / FEATURE / Cria tabela de equipamentos no banco de dados
  src/database/migrations/20200205002642-create-equipments.js
Labels: feature

#9 Adiciona feature de criação de containers
  doc/100-customizacao-lmp-platform.md
  src/app/controllers/ContainerController.js
  src/app/models/Container.js
  src/database/index.js
  src/database/migrations/20200204184831-create-containers.js
  src/routes.js
Labels: feature

#10 API-CLIENT / FIX / Deleted variable duplicate after merge
  src/routes.js
Labels: feature

#14 Criação do model e cadastro de rooms
  src/app/controllers/RoomController.js
  src/database/index.js
  src/routes.js
Labels: feature

#18 Criação do database para tools
  README.md
  src/app/controllers/ToolController.js
  src/app/models/Tool.js
  src/database/index.js
  src/database/migrations/20200204173345-create-tools.js
  src/routes.js
Labels: feature

#20 API-CLIENT / FIX / Corrige migration de adição de coluna na tabela users
  src/database/migrations/20200204182326-add-avatar-field-to-users.js
Labels: bug

#19 Correção do model Room.js adicionando atributo 'container' em sua inicialização
  src/app/models/Room.js
  src/database/index.js
Labels: bug

#21 Criação do required() e função update para o ToolController.js
  src/app/controllers/ToolController.js
  src/app/models/Tool.js
  src/database/index.js
  src/database/migrations/20200204173345-create-tools.js
  src/routes.js
Labels: feature

#22 Correção do erro "SequelizeDatabaseError: relation "equipment" does not exist"
  src/app/models/Equipment.js
  src/database/migrations/20200205002642-create-equipment.js
  src/routes.js
Labels: bug

#23 Criar model e loader de equipment
  src/app/controllers/EquipmentController.js
  src/app/models/Equipment.js
  src/database/index.js
  src/database/migrations/20200205002642-create-equipment.js
  src/routes.js
Labels: feature

#25 Criação de link entre tabelas de rooms e containers
  src/app/models/Container.js
  src/database/migrations/20200204184831-create-containers.js
Labels: feature

#26 Cria método de atualização de dados dos containers
  src/app/controllers/ContainerController.js
  src/routes.js
Labels: feature

#27 Reduz linha de código conforme sugestão de revisor
  src/app/controllers/ContainerController.js
Labels: feature

#29 Correção de alguns erros do último pull request
  src/app/models/Tool.js
  src/database/migrations/20200210221649-add-container-field-to-tools.js
Labels: feature

#30 Cria model, controller e migration de 'Labs' com validações e método update
  src/app/controllers/LabController.js
  src/app/models/Lab.js
  src/database/index.js
  src/database/migrations/20200210194724-create-labs.js
  src/routes.js
Labels: feature

#31 Revisão e atualização do model e controller de Rooms
  src/app/controllers/RoomController.js
  src/app/models/Room.js
  src/routes.js
Labels: feature

#32 API-CLIENT / FIX / Remoção de 'containers' da migration de rooms
  src/database/migrations/20200130211038-create-rooms.js
Labels: feature

#33 Integração entre a tabela de rooms e a tabela de labs
  src/app/controllers/RoomController.js
  src/app/models/Room.js
  src/database/migrations/20200130211038-create-rooms.js
Labels: feature

#34 Reduz quantidade de migrations
  src/database/migrations/20200130211037-create-labs.js
  src/database/migrations/20200204173345-create-containers.js
  src/database/migrations/20200204173345-create-tools.js
  src/database/migrations/20200210221649-add-container-field-to-tools.js
Labels: enhancement

#36 API-CLIENT / FEATURE / 02 Listagem de prestadores de serviço
  src/app.js
  src/app/controllers/ProviderController.js
  src/app/models/File.js
  src/app/models/User.js
  src/routes.js
  tmp/uploads/c983a997ff74fa9468e8be9721a9a9c4.png
Labels: feature

#39 Adiciona 'created_by' e 'updated_by' para rooms e tools
  src/app/controllers/ContainerController.js
  src/app/controllers/RoomController.js
  src/app/controllers/ToolController.js
  src/app/models/Room.js
  src/app/models/Tool.js
  src/database/migrations/20200130211038-create-rooms.js
  src/database/migrations/20200204173345-create-tools.js
Labels: feature

#38 Atualização da tabela de equipamentos no geral
  doc/02-iniciando-back-end-do-gobarber.md
  src/app/controllers/EquipmentController.js
  src/app/models/Equipment.js
  src/database/migrations/20200205002642-create-equipment.js
  src/routes.js
Labels: feature

#40 Correção do export default Appointment e adição de comentários
  src/app/models/Appointment.js
  src/database/migrations/20200213180628-create-appointments.js
Labels: bug, documentation

#43 API-CLIENT / FEATURE / 03-04 Agendamento de serviço
  src/app/controllers/AppointmentController.js
  src/routes.js
Labels: feature

#44 API-CLIENT / FEATURE / 05 Validações de agendamento
  package.json
  src/app/controllers/AppointmentController.js
  yarn.lock
Labels: feature

#41 Cria método que permite o agendamento de equipamentos
  package.json
  src/app/controllers/BookingController.js
  src/app/controllers/EquipmentController.js
  src/app/controllers/ScheduleController.js
  src/app/models/Booking.js
  src/database/index.js
  src/database/migrations/20200214121652-create-booking.js
  src/routes.js
  yarn.lock
Labels: feature

#45 API-CLIENT / FEATURE / 06 Listando agendamentos do usuário
  src/app/controllers/AppointmentController.js
  src/routes.js
  tmp/uploads/fa7bb1002128fe8e2725152d6b67a945.png
Labels: feature

#42 API-CLIENT / DOCUMENTATION / Documentação de listagem de prestadores
  doc/02-iniciando-back-end-do-lmp-platform.md
  doc/03-continuando-api-do-lmp-platform.md
Labels: documentation

#46 Adição de 'responsible_id' e 'hourly_rate_brl' aos equipamentos
  src/app/controllers/EquipmentController.js
  src/app/models/Equipment.js
  src/database/migrations/20200205002642-create-equipment.js
Labels: feature

#49 Aplica paginação à listagem de agendamentos
  src/app/controllers/AppointmentController.js
Labels: feature

#50 Listando agenda do prestador
  src/app/controllers/ScheduleController.js
  src/routes.js
Labels: feature

#51 Configura MongoDB
  package.json
  src/database/index.js
  yarn.lock
Labels: feature

#47 Agendamentos através do dia e o equipment_id
  src/app/controllers/ScheduleController.js
Labels: feature

#53 API-CLIENT / FIX / Adiciona useUnifiedTopology:true
  src/database/index.js
Labels: bug

#54 Notificando novos agendamentos
  src/app/controllers/AppointmentController.js
  src/app/controllers/RoomController.js
  src/app/schemas/Notification.js
Labels: feature

#55 Listando notificacoes do usuario
  src/app/controllers/AppointmentController.js
  src/app/controllers/NotificationController.js
  src/routes.js
Labels: feature

#56 Marcar notfificacoes como lidas
  src/app/controllers/NotificationController.js
  src/database/index.js
  src/routes.js
Labels: feature

#57 Cria cancelamento de agendamento
  src/app/controllers/AppointmentController.js
  src/routes.js
Labels: feature

#52 Permite o cancelamento de agendamento
  src/app/controllers/BookingController.js
  src/routes.js
Labels: feature
