Repository amaralc/lmp-platform, pull requests merged in 2020-03, with the labels that each got.

#58 Configura nodemailer
  package.json
  src/app/controllers/AppointmentController.js
  src/config/mail.js
  src/lib/Mail.js
  yarn.lock
Labels: feature

#59 Configurando templates de email
  package.json
  src/app/controllers/AppointmentController.js
  src/app/views/emails/cancellation.hbs
  src/app/views/emails/layouts/default.hbs
  src/app/views/emails/partials/footer.hbs
  src/lib/Mail.js
  yarn.lock
Labels: feature

#60 Configurando fila com Redis
  package.json
  src/app/controllers/AppointmentController.js
  src/app/jobs/CancellationMail.js
  src/config/redis.js
  src/lib/Queue.js
  src/queue.js
  yarn.lock
Labels: feature

#61 Adiciona monitoramento de falhas na fila
  src/lib/Queue.js
Labels: feature

#62 Cria listagem de horarios disponiveis
  src/app/controllers/AvailableController.js
  src/routes.js
Labels: feature

#63 Cria campos virtuais no agendamento
  src/app/controllers/AppointmentController.js
  src/app/models/Appointment.js
Labels: feature

#64 Adiciona tratamento de exceções com Sentry
  package.json
  src/app.js
  src/config/sentry.js
  template.js
  yarn.lock
Labels: feature

#65 Configurando variaveis ambiente
  .env.example
  .gitignore
  package.json
  src/app.js
  src/app/models/File.js
  src/config/auth.js
  src/config/database.js
  src/config/mail.js
  src/config/redis.js
  src/config/sentry.js
  src/database/index.js
  src/queue.js
  yarn.lock
Labels: feature

#70 Update dev branch with production scripts
  .gitignore
  package.json
Labels: infrastructure

#71 Deploy to production
  .gitignore
  package.json
Labels: infrastructure

#72 Faz ajustes na API adicionando 'cors' e incluindo models em algumas respostas
  package.json
  src/app.js
  src/app/controllers/ScheduleController.js
  src/app/controllers/SessionController.js
  src/app/controllers/UserController.js
  yarn.lock
Labels: feature

#73 Envia ajustes na API para producao
  package.json
  src/app.js
  src/app/controllers/ScheduleController.js
  src/app/controllers/SessionController.js
  src/app/controllers/UserController.js
  yarn.lock
Labels: feature

#75 Corrigindo nomes que estavam dando conflitos
  src/app/controllers/EquipmentScheduleController.js
  src/routes.js
Labels: enhancement

#74 Atualização de branch dev (backend gobarber concluído) com branch api-client/dev (atualizacoes de itens do lab concluidas)
  doc/02-iniciando-back-end-do-lmp-platform.md
  doc/03-continuando-api-do-lmp-platform.md
  src/app/controllers/BookingController.js
  src/app/controllers/ContainerController.js
  src/app/controllers/EquipmentController.js
  src/app/controllers/EquipmentScheduleController.js
  src/app/controllers/RoomController.js
  src/app/controllers/ToolController.js
  src/app/models/Booking.js
  src/app/models/Equipment.js
  src/app/models/Room.js
  src/app/models/Tool.js
  src/database/index.js
  src/database/migrations/20200130211038-create-rooms.js
  src/database/migrations/20200204173345-create-tools.js
  src/database/migrations/20200205002642-create-equipment.js
  src/database/migrations/20200214121652-create-booking.js
  src/routes.js
Labels: feature

#76 Muda nome de ScheduleController para ProviderScheduleController
  src/app/controllers/ProviderScheduleController.js
  src/routes.js
Labels: bug

#77 Resolução de conflitos entre api-client/dev e dev
  src/app/controllers/ProviderScheduleController.js
  src/routes.js
Labels: bug

#78 Separação de ProviderScheduleController e EquipmentScheduleController
  doc/02-iniciando-back-end-do-lmp-platform.md
  doc/03-continuando-api-do-lmp-platform.md
  src/app/controllers/BookingController.js
  src/app/controllers/ContainerController.js
  src/app/controllers/EquipmentController.js
  src/app/controllers/EquipmentScheduleController.js
  src/app/controllers/ProviderScheduleController.js
  src/app/controllers/RoomController.js
  src/app/controllers/ToolController.js
  src/app/models/Booking.js
  src/app/models/Equipment.js
  src/app/models/Room.js
  src/app/models/Tool.js
  src/database/index.js
  src/database/migrations/20200130211038-create-rooms.js
  src/database/migrations/20200204173345-create-tools.js
  src/database/migrations/20200205002642-create-equipment.js
  src/database/migrations/20200214121652-create-booking.js
  src/routes.js
Labels: feature

#79 API-CLIENT / FEATURE / Lista equipamentos sem necessidade de estar logado na aplicacao
  src/database/index.js
  src/routes.js
Labels: feature

#80 Lista equipamentos sem usuario estar logado
  src/database/index.js
  src/routes.js
Labels: feature
